# Generated by Django 4.2.3 on 2023-07-14 06:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leave", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leave",
            name="leavetype",
            field=models.CharField(
                choices=[
                    ("sick", "Sick Leave"),
                    ("casual", "Casual Leave"),
                    ("emergency", "Emergency Leave"),
                    ("study", "Study Leave"),
                    ("maternity", "Maternity Leave"),
                ],
                default="sick",
                max_length=25,
                null=True,
            ),
        ),
    ]
