# Generated by Django 4.2.3 on 2023-07-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('leave', '0002_alter_leave_leavetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='leavetype',
            field=models.CharField(
                choices=[
                    ('sick', 'Sick Leave'),
                    ('casual', 'Casual Leave'),
                    ('emergency', 'Emergency Leave'),
                    ('study', 'Study Leave'),
                    ('maternity', 'Maternity Leave'),
                    ('bereavement', 'Bereavement Leave'),
                    ('quarantine', 'Self Quarantine'),
                    ('compensatory', 'Compensatory Leave'),
                    ('sabbatical', 'Sabbatical Leave'),
                ],
                default='sick',
                max_length=25,
                null=True,
            ),
        ),
    ]
