app_id: "App ID"
app_secret: "Secret"
redirect: "http://localhost:8000/accounts/callback"
authority: "https://login.microsoftonline.com/common"
scopes:
    - user.read
    - mailboxsettings.read
    - calendars.readwrite
