name: Build and Install Dependencies

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9.16'

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('LeaveMgmt-Django/src/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd LeaveMgmt-Django/LMS
        pip install pylint
        pip install -r requirements.txt

    - name: Install Black
      run: pip install black

    - name: Check code formatting
      run: black --check .

    - name: Run tests with coverage
      run: |
        coverage run manage.py test
        coverage xml
      working-directory: LeaveMgmt-Django/LMS

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./LeaveMgmt-Django/coverage.xml
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    
    - name: Run Pylint
      uses: Silleellie/pylint-github-action@v1
      with:
        package-path: LMS
        python-version: 3.9.16
