name: Super-Linter

on:
  push:
    branches: [ master ]

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Install dependencies
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run Super-Linter
      - name: Run Super-Linter
        uses: github/super-linter@v4.8.0
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_PYTHON: true
          VALIDATE_PYTHON_BLACK: true # For Python formatting
          VALIDATE_PYTHON_PYLINT: true # For Python best-practices and code quality checks
          VALIDATE_JAVASCRIPT_ES: true # For JavaScript linting
          VALIDATE_CSS: true # For CSS linting
          VALIDATE_HTML: true # For HTML linting
          VALIDATE_ALL_CODEBASE: false # To disable the other linters
